"""rename create_data/updated_data to create_date/update_date

Revision ID: 184aba947e20
Revises: 1d4b16306fe7
Create Date: 2026-08-29 17:13:34.857759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184aba947e20'
down_revision: Union[str, Sequence[str], None] = '1d4b16306fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('create_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('tasks', sa.Column('update_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('tasks', 'updated_data')
    op.drop_column('tasks', 'create_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('create_data', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('tasks', sa.Column('updated_data', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('tasks', 'update_date')
    op.drop_column('tasks', 'create_date')
    # ### end Alembic commands ###
