"""addind relation to tasks

Revision ID: 456de53611cf
Revises: 3582d46a3802
Create Date: 2026-09-01 19:49:47.831476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "456de53611cf"
down_revision: Union[str, Sequence[str], None] = "3582d46a3802"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_user_tasks", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_tasks", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
